### PR TITLE
Fix bank code getter and update list of banks

### PR DESCRIPTION
**Pull request by Swejzi**
Your package helps me, but need update :-)

### CODE REVIEW

**Comment by ondrakub** [comment]
thank you!
test failed because `getCode` method has to return int, sprintf return string and I use tabs for indentation. Can you fix both? 

I will plan to release version 2.0 with support of PHP 7 and type hint and return type.

**Comment by ondrakub** [comment]
I realize one thing now. There are methods parse and valid, so if code part does not have 4 digits, an exception should be thrown. `getCode` method does not need to be changed. But never mind. I will do big refactoring in version 2.0.

**Comment by Swejzi** [comment]
Sorry for failed test, I tried fix it.

If bank code starts with zero (0800), function getCode return int 800, and key 800 in $banks doesnt exist.

**Comment by ondrakub** [comment]
@Swejzi thx! version [1.3](https://github.com/ondrakub/bank-php/releases/tag/v1.3) is out

**Pull request merged**
